GET http://localhost:3000/todos/?status=TO%20DO

###
GET http://localhost:3000/todos/2

###
GET http://localhost:3000/agenda/?date=2021-4-2

###

POST http://localhost:3000/todos
Content-Type: application/json

{
 "id": 10,
 "todo": "Help Lakshmi",
 "priority": "HIGH",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "022-13-35"
}

###
PUT http://localhost:3000/todos/1
Content-Type: application/json 

{ "dueDate": "2021-14-12" }

###
DELETE http://localhost:3000/todos/1